import React from "react";

import styles from './home.module.css';

function Home(){
    return(
        <section className={styles.container}>
            <h2 className={styles.h2}>Home</h2>
            <p className={styles.p}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus et sem sit amet tempor. Mauris auctor risus placerat, ullamcorper nisi dapibus, consectetur nunc. Morbi vel est a lacus vehicula laoreet et eget ipsum. Quisque a eleifend lacus, in dapibus augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam fermentum malesuada lorem, id iaculis purus dictum non. Curabitur ullamcorper vitae libero ultrices faucibus. Morbi scelerisque vel nunc id dignissim. Aliquam tempor sed magna a facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus ultricies tortor suscipit turpis rhoncus, sed faucibus elit aliquam. Ut id urna sed turpis finibus mollis. Fusce at nulla risus. Quisque libero justo, dapibus at ornare a, rutrum id velit. Integer vitae volutpat metus.</p>
            <p className={styles.p}>Nunc consequat tellus in magna tincidunt, lacinia aliquam sem vulputate. Curabitur placerat, sem vel mollis cursus, ante magna convallis lorem, eget fringilla tortor diam a magna. Aenean leo odio, convallis id nisi vel, aliquam luctus lacus. Curabitur in auctor enim. Curabitur orci arcu, eleifend nec risus a, ullamcorper placerat leo. In quis mauris mi. Maecenas eu tortor a turpis ultrices laoreet et et eros. Duis lobortis volutpat ligula ac luctus. Proin at sapien est. Nunc dignissim suscipit ante sed efficitur. Vivamus viverra, erat vitae dapibus rutrum, risus enim dignissim massa, quis aliquet neque augue eget libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta vitae mauris sit amet eleifend.</p>
            <p className={styles.p}>Nunc consequat tellus in magna tincidunt, lacinia aliquam sem vulputate. Curabitur placerat, sem vel mollis cursus, ante magna convallis lorem, eget fringilla tortor diam a magna. Aenean leo odio, convallis id nisi vel, aliquam luctus lacus. Curabitur in auctor enim. Curabitur orci arcu, eleifend nec risus a, ullamcorper placerat leo. In quis mauris mi. Maecenas eu tortor a turpis ultrices laoreet et et eros. Duis lobortis volutpat ligula ac luctus. Proin at sapien est. Nunc dignissim suscipit ante sed efficitur. Vivamus viverra, erat vitae dapibus rutrum, risus enim dignissim massa, quis aliquet neque augue eget libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta vitae mauris sit amet eleifend.</p>
            <p className={styles.p}>Nunc consequat tellus in magna tincidunt, lacinia aliquam sem vulputate. Curabitur placerat, sem vel mollis cursus, ante magna convallis lorem, eget fringilla tortor diam a magna. Aenean leo odio, convallis id nisi vel, aliquam luctus lacus. Curabitur in auctor enim. Curabitur orci arcu, eleifend nec risus a, ullamcorper placerat leo. In quis mauris mi. Maecenas eu tortor a turpis ultrices laoreet et et eros. Duis lobortis volutpat ligula ac luctus. Proin at sapien est. Nunc dignissim suscipit ante sed efficitur. Vivamus viverra, erat vitae dapibus rutrum, risus enim dignissim massa, quis aliquet neque augue eget libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta vitae mauris sit amet eleifend.</p>
        </section>
    )
}

export default Home;